kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stable-diffusion-pvc
  namespace: stephan-devspaces
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem