apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: stephan-devspaces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: OLLAMA_BASE_URL
          value: 'http://ollama-service.stephan-devspaces.svc.cluster.local'
        - name: AUTOMATIC1111_BASE_URL
          value: 'http://stable-diffusion-service.stephan-devspaces.svc.cluster.local:7860/'
        - name: ENABLE_IMAGE_GENERATION
          value: 'True'
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
        securityContext:
          runAsUser: 0
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: open-webui-pvc
